### ISSUE TITLE
Delete project from project dashboard

### ISSUE THREAD

**Issue by techster10173** [Three0Dev/Three0#21]

**Comment by sparshypop7** [comment]
I believe we shouldn't have the feature of deleting a project on the project dashboard because it is too available for the developer to delete their project. Just like how github has only one area to delete a repository and the fact that you need to type out a phrase to delete the repo makes it harder for one to accidentally delete a project. So I think the project deletion method we have on the home page is all we need to delete a project, make it harder for the developer to delete so the developer can make sure he/she is certain of deleting the project
