### ISSUE TITLE
Delete databases on project delete

### ISSUE THREAD

**Issue by techster10173** [Three0Dev/Three0#28]

**Comment by sparshypop7** [comment]
Having a delete option on the project dashboard may not be feasible because the convenience of deleting a developer's entire project should not be more accessible, but somewhat more challenging and more secure. When deleting a repository on GitHub, the developer needs to write a phrase to confirm the deletion and the deletion of the repository is harder to find. So the current implementation of deleting a project on the project home page should be the only implementation of deleting a project because it requires the developer to interact and require more effort to delete, which prompts the developer to think and confirm before deleting their project.

**Comment by techster10173** [comment]
This has been reopened as the closing statement is not relevant to the issue. This issue is still valid as of this time.

**Comment by sparshypop7** [comment]
That was for a different issue, was a mistake.
